# Generated by Django 2.2.4 on 2019-08-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=20)),
                ('aadhar_num', models.CharField(max_length=20)),
                ('finger_print', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=255)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionConstituency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Constituency')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartyCandidate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aadhar_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AadharDetail')),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Constituency')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Election')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Party')),
            ],
        ),
        migrations.DeleteModel(
            name='AadharData',
        ),
        migrations.AddField(
            model_name='aadhardetail',
            name='constituency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Constituency'),
        ),
    ]
